resource "checkpoint_management_host" "Internal_Host_31" {}
resource "checkpoint_management_host" "Internal_Host_32" {}
resource "checkpoint_management_host" "Internal_Host_33" {}
resource "checkpoint_management_host" "Internal_Host_34" {}
resource "checkpoint_management_host" "Internal_Host_35" {}
resource "checkpoint_management_host" "Internal_Host_36" {}
resource "checkpoint_management_host" "Internal_Host_37" {}
resource "checkpoint_management_host" "Internal_Host_38" {}
resource "checkpoint_management_host" "Internal_Host_39" {}
resource "checkpoint_management_host" "Internal_Host_40" {}
