resource "checkpoint_management_host" "Internal_Host_61" {}
resource "checkpoint_management_host" "Internal_Host_62" {}
resource "checkpoint_management_host" "Internal_Host_63" {}
resource "checkpoint_management_host" "Internal_Host_64" {}
resource "checkpoint_management_host" "Internal_Host_65" {}
resource "checkpoint_management_host" "Internal_Host_66" {}
resource "checkpoint_management_host" "Internal_Host_67" {}
resource "checkpoint_management_host" "Internal_Host_68" {}
resource "checkpoint_management_host" "Internal_Host_69" {}
resource "checkpoint_management_host" "Internal_Host_70" {}
